In [17]:
import pandas as pd
import numpy as np
import io

In [2]:
csv_data = """order_id,customer,city,total_bill,tip,table_size
1,Alice,Tel Aviv,45.50,8.00,4
2,Bob,Haifa,22.30,3.50,2
3,Carol,Tel Aviv,67.80,12.00,6
4,David,Jerusalem,15.20,2.00,2
5,Eve,Haifa,89.90,15.00,8
6,Frank,Tel Aviv,33.40,5.50,3
7,Grace,Jerusalem,51.00,9.00,4
8,Henry,Haifa,28.60,4.00,2
9,Iris,Tel Aviv,74.20,13.50,5
10,Jake,Jerusalem,19.80,2.50,2"""

In [5]:
#1
# Load CSV string into DataFrame
df = pd.read_csv(io.StringIO(csv_data))

# Display DataFrame information
print(df.info())

# Display descriptive statistics transposed
print(df.describe().transpose())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    10 non-null     int64
 1   customer    10 non-null     str
 2   city        10 non-null     str
 3   total_bill  10 non-null     float64
 4   tip         10 non-null     float64
 5   table_size  10 non-null     int64
dtypes: float64(2), int64(2), str(2)
memory usage: 612.0 bytes
None
            count   mean        std   min     25%    50%    75%   max
order_id     10.0   5.50   3.027650   1.0   3.250   5.50   7.75  10.0
total_bill   10.0  44.77  25.530159  15.2  23.875  39.45  63.60  89.9
tip          10.0   7.50   4.743416   2.0   3.625   6.75  11.25  15.0
table_size   10.0   3.80   2.043961   2.0   2.000   3.50   4.75   8.0

In [6]:
#2
df['price_per_person'] = df['total_bill'] / df['table_size']
df

,order_id,customer,city,total_bill,tip,table_size,price_per_person
0,1,Alice,Tel Aviv,45.5,8.0,4,11.375000
1,2,Bob,Haifa,22.3,3.5,2,11.150000
2,3,Carol,Tel Aviv,67.8,12.0,6,11.300000
3,4,David,Jerusalem,15.2,2.0,2,7.600000
4,5,Eve,Haifa,89.9,15.0,8,11.237500
5,6,Frank,Tel Aviv,33.4,5.5,3,11.133333
6,7,Grace,Jerusalem,51.0,9.0,4,12.750000
7,8,Henry,Haifa,28.6,4.0,2,14.300000
8,9,Iris,Tel Aviv,74.2,13.5,5,14.840000
9,10,Jake,Jerusalem,19.8,2.5,2,9.900000

In [7]:
#3
df[df['price_per_person'] > 12]

,order_id,customer,city,total_bill,tip,table_size,price_per_person
6,7,Grace,Jerusalem,51.0,9.0,4,12.75
7,8,Henry,Haifa,28.6,4.0,2,14.30
8,9,Iris,Tel Aviv,74.2,13.5,5,14.84

In [13]:
#4
def size_s_l(table_size):
    return 'Large' if table_size >= 4 else 'Small'

df['table_type'] = df['table_size'].apply(size_s_l)
df

,order_id,customer,city,total_bill,tip,table_size,price_per_person,table_type
0,1,Alice,Tel Aviv,45.5,8.0,4,11.375000,Large
1,2,Bob,Haifa,22.3,3.5,2,11.150000,Small
2,3,Carol,Tel Aviv,67.8,12.0,6,11.300000,Large
3,4,David,Jerusalem,15.2,2.0,2,7.600000,Small
4,5,Eve,Haifa,89.9,15.0,8,11.237500,Large
5,6,Frank,Tel Aviv,33.4,5.5,3,11.133333,Small
6,7,Grace,Jerusalem,51.0,9.0,4,12.750000,Large
7,8,Henry,Haifa,28.6,4.0,2,14.300000,Small
8,9,Iris,Tel Aviv,74.2,13.5,5,14.840000,Large
9,10,Jake,Jerusalem,19.8,2.5,2,9.900000,Small

In [14]:
#5
df = df.set_index('customer')
df.loc['Alice': 'Carol']

,order_id,city,total_bill,tip,table_size,price_per_person,table_type
customer,,,,,,,
Alice,1,Tel Aviv,45.5,8.0,4,11.375,Large
Bob,2,Haifa,22.3,3.5,2,11.150,Small
Carol,3,Tel Aviv,67.8,12.0,6,11.300,Large

In [15]:
#6
l_f_3 = pd.concat(
    [df.head(3), df.tail(3)],
    axis=0,
    ignore_index=True   # resets the index to 0,1,2,3,4
)
l_f_3

,order_id,city,total_bill,tip,table_size,price_per_person,table_type
0,1,Tel Aviv,45.5,8.0,4,11.375,Large
1,2,Haifa,22.3,3.5,2,11.150,Small
2,3,Tel Aviv,67.8,12.0,6,11.300,Large
3,8,Haifa,28.6,4.0,2,14.300,Small
4,9,Tel Aviv,74.2,13.5,5,14.840,Large
5,10,Jerusalem,19.8,2.5,2,9.900,Small

In [18]:
#7
def value_label(total_bill, tip):
    return 'High Value' if total_bill > 50 and tip > (total_bill * 10) / 100 else 'Standard'

df['value_label'] = np.vectorize(value_label)(
    df['total_bill'],
    df['tip']
)
df

,order_id,city,total_bill,tip,table_size,price_per_person,table_type,value_label
customer,,,,,,,,
Alice,1,Tel Aviv,45.5,8.0,4,11.375000,Large,Standard
Bob,2,Haifa,22.3,3.5,2,11.150000,Small,Standard
Carol,3,Tel Aviv,67.8,12.0,6,11.300000,Large,High Value
David,4,Jerusalem,15.2,2.0,2,7.600000,Small,Standard
Eve,5,Haifa,89.9,15.0,8,11.237500,Large,High Value
Frank,6,Tel Aviv,33.4,5.5,3,11.133333,Small,Standard
Grace,7,Jerusalem,51.0,9.0,4,12.750000,Large,High Value
Henry,8,Haifa,28.6,4.0,2,14.300000,Small,Standard
Iris,9,Tel Aviv,74.2,13.5,5,14.840000,Large,High Value
Jake,10,Jerusalem,19.8,2.5,2,9.900000,Small,Standard

In [24]:
#8
df.iloc[9:6:-1]

,order_id,city,total_bill,tip,table_size,price_per_person,table_type,value_label
customer,,,,,,,,
Jake,10,Jerusalem,19.8,2.5,2,9.90,Small,Standard
Iris,9,Tel Aviv,74.2,13.5,5,14.84,Large,High Value
Henry,8,Haifa,28.6,4.0,2,14.30,Small,Standard

In [23]:
df.iloc[2:7:2]

,order_id,city,total_bill,tip,table_size,price_per_person,table_type,value_label
customer,,,,,,,,
Carol,3,Tel Aviv,67.8,12.0,6,11.3000,Large,High Value
Eve,5,Haifa,89.9,15.0,8,11.2375,Large,High Value
Grace,7,Jerusalem,51.0,9.0,4,12.7500,Large,High Value